#!/usr/bin/env bash

echo "Atualização detectada no repositório!"
echo "Aplicando as novas configurações do NixOS..."

CURRENT_HOST=$(hostname)

sudo nixos-rebuild switch --flake .#$CURRENT_HOST

if [ $? -eq 0 ]; then
    echo "✅ Sistema atualizado com sucesso!"
else
    echo "❌ Erro ao atualizar o sistema. Verifique os logs acima."
fi
